### ISSUE TITLE
Fully remove all XRP from an account.

### ISSUE THREAD

**Issue by michpalmerdesign** [ripple/ripple-client#754]
I understand this might have been mentioned in an issue before, sorry if this is completely a dupe. But I do think it should be possible to remove all XRP from an account rendering it inert. Perhaps multiple warnings can pop up and this might permanently delete the account, but if someone doesn't feel like maintaining a wallet anymore, and they want to consolidate accounts, it should be possible to move all xrp from accounts the owner no longer wants to use. Obviously this would require all trust lines, addresses, bids/offers etc be manually removed first. 

What do you think?

**Comment by orll** [comment]
I'm very disappointed. This looks as a simple charge. Just as banks do.

**Comment by ncypher** [comment]
Fucking Banks!

**Comment by ncypher** [comment]
I take this back. It is kind of ingenius. Think about it. It is a scarcity engine. Think of those 20 Ripple coins as membership fee for a Millionaire's Club. :-)

**Comment by JoelKatz** [comment]
The base reserve is currently 20 XRP. If your account has a higher reserve, it's because you own objects in the ledger (trust lines, offers, escrows, or the like) and you can remove them to lower your reserve.

**Comment by luigimannoni** [comment]
Which at the actual price is almost $20 plus almost $5 for each trust line... I did came to know this only after opening a second wallet (yes, my bad should've researched it) and now I find myself with pretty much 2 unusable wallets.
Any plan to lower the reserve down to an appreciable amount, or a way to definitely destroy a wallet taking the reserve to another wallet if we don't need it anymore?

**Comment by fulvioMorelli** [comment]
Dear and sorry, so no way to remove all XRP from a wallet?

**Comment by armata** [comment]
Why can't the base reserve amount be changed to 1 or 2 XRP? I literally have ~62 USD (20 XRP) sitting in my Ripple wallet and I can't do anything about it.

**Comment by MBid2018** [comment]
Sharing same frustrations as everyone above. They have to lower that rate, especially as XRP keeps going up. Today its ~62USD tomorrow it'll be 100 and so on and so forth. Does Ripple Wallet have a plan for adjusting when/if this scenario comes forth?

**Comment by gulbis** [comment]
Gatehub actually locks 50XRP, so the "Wallet" costs at least 150$ at 3$ price and the price is increasing... With 20$ XRP it would be a 1000$!

**Comment by abhilash1in** [comment]
Many exchanges in my country takes ages to complete verification and onboarding. To make it quicker, I generated a wallet address and sent 30XRP. Now what's rightfully mine is just 10XRP? That loss makes it terrible, especially at the current rates!

**Comment by prestonw** [comment]
This reserve fee needs to go, or the currency is invalid. If you want an account creation fee then add that as a one off charge sent to a wallet at the current XRP rate then whatever is in the account is ours. If it's a technical challenge around deleting an account this is simply met by keeping a very low balance (0.01XRP). I don't believe there will be a flood of transactions that breaks the network, if there is simply revert the change and look for an alternative solution, but it feels like a unnecessary charge at the moment especially with those who created a second wallet to test out transferring to only find they basically burnt that balance.

**Comment by orll** [comment]
Just imagine a poor family transfering 25 XRP to their wallet without knowing the would lose 20 XRP. 
I want to have the right to choose. I think this is not fair.

**Comment by fawadmirza** [comment]
This also means that Ripple XRP will never ever be the same value as say... Bitcoin or Ether. Its just a very flawed concept. Imagine having to buy 20btc just to have a wallet address, thats $300k down the drain. Even at ether price it is insane. If they do want the currency to go somewhere they will have Either remove this fees/or charge USD equivalent of xrp. Its not sustainable like this.

**Comment by fulvioMorelli** [comment]
Fee in btc and eth need to pay miner that verify transaction. In xrp the trust line take fee commission to veryfy transaction like btc. Ten days ago i send xrp from aper wallet to gatehub, i paied the trustlne transaction, about 1 xrp to send 90xrp.

Inviato da Yahoo Mail su Android 
 
  Il gio, 11 gen, 2018 alle 10:19, fawadmirza<notifications@github.com> ha scritto:   
This also means that Ripple XRP will never ever be the same value as say... Bitcoin or Ether. Its just a very flawed concept. Imagine having to buy 20btc just to have a wallet address, thats $300k down the drain. Even at ether price it is insane. If they do want the currency to go somewhere they will have Either remove this fees/or charge USD equivalent of xrp. Its not sustainable like this.

**Comment by Tyrael** [comment]
just putting this out here, there is a way for change the value of account_reserve:

https://ripple.com/build/reserves/#changing-the-reserve-requirements

> Changing the Reserve Requirements
> The XRP Ledger has a mechanism to adjust the reserve requirements for long-term changes in the value of XRP. Any changes have to be approved by the consensus process. See Fee Voting for more information.

https://ripple.com/build/fee-voting/

> account_reserve | Minimum amount of XRP, in drops, that an account must have on reserve. This is the smallest amount that can be sent to fund a new account in the ledger. | 20000000 (20 XRP)

**Comment by abhilash1in** [comment]
@Tyrael you mean we can all come together and influence the network? (If you're running a full `rippled` validator)

**Comment by abhilash1in** [comment]
This is exactly why we are trying to move away from a centralized ecosystem!

**Comment by armata** [comment]
Yep. We could contact Ripple and tell them to lower the reserve though.

**Comment by fulvioMorelli** [comment]
*just putting this out here, there is a way for change the value of account_reserve:https://ripple.com/build/reserves/#changing-the-reserve-requirements
Changing the Reserve Requirements
The XRP Ledger has a mechanism to adjust the reserve requirements for long-term changes in the value of XRP. Any changes have to be approved by the consensus process. See Fee Voting for more information.
https://ripple.com/build/fee-voting/
account_reserve | Minimum amount of XRP, in drops, that an account must have on reserve. This is the smallest amount that can be sent to fund a new account in the ledger. | 20000000 (20 XRP)
*to change minimun reserves you must know very well, program language. For normal user it is very hard to do. 

    Il Giovedì 11 Gennaio 2018 14:42, Ferenc Kovacs <notifications@github.com> ha scritto:
 

 just putting this out here, there is a way for change the value of account_reserve:https://ripple.com/build/reserves/#changing-the-reserve-requirements
Changing the Reserve Requirements
The XRP Ledger has a mechanism to adjust the reserve requirements for long-term changes in the value of XRP. Any changes have to be approved by the consensus process. See Fee Voting for more information.
https://ripple.com/build/fee-voting/
account_reserve | Minimum amount of XRP, in drops, that an account must have on reserve. This is the smallest amount that can be sent to fund a new account in the ledger. | 20000000 (20 XRP)

**Comment by JoelKatz** [comment]
The XRP Ledger's design makes accounts primary objects in the system. This is a design difference compared to systems like bitcoin. This has advantages and disadvantages.

Among the advantages are:

1. You can change an account's key to resecure it without having to change your receiving address
2. An account can specify the assets it wishes to receive
3. Accounts can specify multisigning lists and maintain them
4. Accounts can place offers to trade assets
5. You don't have to specify the exact funds you're using to make a payment
And several more.

But this also comes at a cost -- there's a scalability limit on the number of accounts because each account persists in the ledger.

The account reserve acts to ration ledger space. Without it, the number of accounts could grow without bound, imposing costs on everyone who runs a node on the network. To ensure that the value added by an account is comparable to the costs imposed, the reserve is set.

The reserve is vastly superior to a fixed fee. For one thing, if the reserve is deemed to be higher than needed to be to serve its intended function, it can be lowered, releasing XRP that was previously locked. For another thing, it eliminates the confusion surrounding statements like, "You'll get 90 XRP if you already have an account or 70 XRP if you don't". Lastly, the reserve system easily accommodates increasing the reserve for additional ledger space for things like offers, trust lines, multisigner lists, and so on.

We have good evidence that the reserve is currently too low to serve its intended function. Poloniex senselessly forces every customer who wishes to deposit XRP to create an account. The purpose of the reserve is to discourage this, and it isn't doing that.

We could add a feature to completely delete an account and return the reserve to another account. The problem with doing this is that if funds are ever sent to the deleted account's address, the account would be re-created. Nothing would reliably prevent someone from replaying the account's previous transactions to consume those funds.

And it's important to understand that when you make changes to a public ledger system, that imposes costs on everyone who uses that system. Previously, you could rely on an account that was present to always be present. After such a chance, you cannot. **Everyone** who uses the system would have to evaluate what effect that has on everything they do.

**Comment by fulvioMorelli** [comment]
Ok, but if I have only a wallet I can't change reserves. right?. Anyone coul become validator? Sorry if I do this question but i would like to understand

**Comment by JoelKatz** [comment]
Anyone can become a validator and everyone can choose which validators they wish to listen to. At this time, Ripple is recommending that people only listen to five validators operated by Ripple and their own validator if they run one. We are working very hard to change this as we very much want diversity of the stakeholders. See:
https://ripple.com/dev-blog/decentralization-strategy-update/

**Comment by fulvioMorelli** [comment]
ok, is one become validator he must leave PC work like server 24/24H, right?

**Comment by fulvioMorelli** [comment]
> Anyone can become a validator and everyone can choose which validators they wish to listen to. At this time, Ripple is recommending that people only listen to five validators operated by Ripple and their own validator if they run one. We are working very hard to change this as we very much want diversity of the stakeholders. See:
https://ripple.com/dev-blog/decentralization-strategy-update/

Ok, I'm dummies, i need exemple to understand. I have one paper wallet 20xrp minimum, one gatehub wallet 50 xrp minimum and one kraken wallet 20 xrp minimum, If I want remove all xrp from gatehub and kraken wallet, if I'm a validator, Can do it?

**Comment by sublimator** [comment]
Would u prefer the system get drowned out with too man txns?

There is real cost to store an account.

If anything, it should be more.

There are too many gateways creating an account per custmer for those
paying attention. Some are not using destination tags.

**Comment by armata** [comment]
Well I don't think a 40$ account cost is reasonable. 5$ or 10$ is fine
though IMHO

On Thu, Jan 11, 2018 at 7:30 PM, Nicholas Dudfield <notifications@github.com

**Comment by fulvioMorelli** [comment]
`Would u prefer the system get drowned out with too man txns?

There is real cost to store an account.

If anything, it should be more.

There are too many gateways creating an account per custmer for those
paying attention. Some are not using destination tags.`
Ok, you're right, but if xrp reach peraphs 6-7$ and you have 3 wallet you lose 360$. If I want close my wallet, Ripple network must give me back all xrp. Try to go to your bank to close your account, if they said to you, "Ehy, ok you can close but you must leav us 360$" It's crazy. When I'll close my wallet gatehub or anyelse must give me back all xrp

**Comment by Tyrael** [comment]
@JoelKatz you already explained this in your original comment here 4 years ago, but seeing the other clueless comments I guess it was needed to be repeated.

personally I think that if the prices hold the reserve fees should be lowered otherwise Ripple will be unfeasible for smalltime investors (which can be totally valid to ignore with your business case).

**Comment by fulvioMorelli** [comment]
repeat, I find right that wallet need minimum reserves to remain active, but when someone want close it, must be there a way to remove all xrp. Or write to ripple network or with special key or something else. I'm small investor, I belive in xrp project, but in future maybe I'll want close my wallet or reduce it from three to one.

**Comment by abhilash1in** [comment]
@JoelKatz @Tyrael How about maintaining a ledger for deleted accounts and not let anything be sent to it (and thus prevent re-creation of the account)? Would this allow for permanent safe deletion of accounts? Will this require any resources any lower than the current system?

**Comment by JoelKatz** [comment]
@abhilash1in That could be done. There are a few problems with it though.

1. It would still require some ledger space, though less than what's currently needed.

2. We'd have to come up with some efficient way to store the removed accounts and some way to look them up in the code that creates a new account.

3. We'd have to fully audit all the rippled transaction code to make sure that all code paths account for the possibility that an account may cease to exist.

4. Everyone who uses the ledger will have to audit their code to make sure it accounts for the possibility that an account that previously existed no longer exists.

5. Everyone who uses the ledger will have to handle the new case where an XRP payment fails because the account could not be created, that means extra work for every exchange that supports XRP.

**Comment by JoelKatz** [comment]
@fulvioMorelli This is an inherent issue with any open, public system. Everything you do imposes costs on everyone else. Without some costs imposed on your to compensate, those bent on harming the system can simply flood it with junk. Every system is limited to those use cases for which its advantages are advantageous and its disadvantages are manageable. This is a disadvantage of XRP's ledger structure. It has compensating advantages, and that's why it was designed that way.

But if the disadvantages outweigh the advantages for your use case, consider using some system that better fits your use case. We will also work as hard as we can on reducing those disadvantages. We are currently focusing scaling effort on reducing the memory consumption of rippled and reducing the costs associated with the use of ledger space. If the reserve comes down in the future, you will be able to transfer the difference out.

There is always the option of using hosted wallets for smaller amounts, though I understand the downsides of holding assets on an exchange or trusting someone else. There is no perfect solution at this time.

**Comment by arektdev** [comment]
This is closed, but there needs to be a notification to users stating that you'll never be able to retrieve the minimum XRP once deposited into Exodus. Many people wouldn't use XRP if they knew this.

**Comment by btemtd** [comment]
> We don't know of any secure way to do this. If the account is deleted, there's nothing to prevent the account from being re-created. And if that happens, all the old transactions would be valid again. The account must remain in the ledger to hold the information that the transactions have already been applied. This breaks our wallet security model and our transaction idempotence model.



> We don't know of any secure way to do this. If the account is deleted, there's nothing to prevent the account from being re-created. And if that happens, all the old transactions would be valid again. The account must remain in the ledger to hold the information that the transactions have already been applied. This breaks our wallet security model and our transaction idempotence model.
-------------------------------------------------------------------------------------------------------------


Hi David can you elaborate on this as this does not make any sense to me, you say if i open up some new wallet and generate a random address ( a 3rd party XRP wallet which is not tied to any ripple tool) .. How does bitcoin generate 100000s of addresses and then throw em away like nothing. How does any coin do the same and stop someone else generating the same address, i heard it doesn't and the chances of generating the same address  in btc is like finding a sand particle on all the beaches in the world then times 1000 planet and all there beaches... some stupid explanation like that. But I am interested in where you say when a xrp wallet is created are you saying it an never be generate, is that because when you generate a wallet its connect to the XRPL? And in that case does this mean there are no such things as offline xrp wallet generators, which there is so this is where it doesnt make sense. because then anyone can generate someone address and then have access to there funds not just tx IDS
