### ISSUE TITLE
2 usernames and password indentical

### ISSUE THREAD

**Issue by noelmal** [ripple/ripple-client#758]
I made a wallet with a username and pw like a day later signing in it kept telling me no wallet with that user name and pw could be found. so I signed up again. 

later checked my details and found i was definitely orginally typin my correct signup details. tested this by signup twice in a row with same username and pw and it let me do 2 the same? what gives?

what if 2 entirely different people did the same?

**Comment by ripplething** [comment]
@vhpoet Can you send me the 30,000 I lost due to this issue?  I’m a little late to the party but I’ve got all the documentation where ripple support said my coins couldn’t be recovered without the secret key?  They failed to mention that there had been issues and changes made that caused this to happened even when I explained the bug to them.   

Thanks!
